---
- name: Test Arista Switch Connection
  hosts: switch1
  gather_facts: no

  vars:
    ansible_become: yes
    ansible_become_method: enable

  tasks:
   ## - name: Show version on the switch
     # arista.eos.eos_command:
      #  commands:
       #   - show version
    #  register: result

    #- name: Display the output
     # debug:
      #  var: result.stdout_lines

    - name: Set hostname
      arista.eos.eos_config:
        lines:
          - hostname LAB-SW1
          - router bgp 400
          -  router-id 10.10.10.2
          -  distance bgp 20 200 200
          -  neighbor 10.10.10.1 remote-as 6501
          -  neighbor 10.10.13.2 remote-as 6503
          -  network 5.5.5.0/24
          -  redistribute connected
          - int eth1
          -  ip address 7.7.7.7/24


